version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: "http://localhost:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
